import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../pages/Layouts/Layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paikari.store</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <Layout />


    </div>
  )
}
